# rename this to config.yml

masterDir: "C:/Users/ggggg/Desktop/boards_example"
# csvList:
  # - fileLists/example.csv
  # - fileLists/misc.csv
  # - fileLists/onSsd.csv
  # - fileLists/pinterest.csv
imageLists:
  # - imageLists/exampleImageLinks.txt
  - imageLists/loremPicsum.txt
  - picsum_imageList.txt
directories:
  # - 
margin: 10
col_count: 6
paginate: True
page_size: 42
padding: 3      # this is padding of the html page numbers. don't change if you don't know what you're doing.
tableName: image_cache
remote_url: https://github.com/flynnsharwood/exampleBoard.git   # this is for the repo you would like to push to
gitUsername: flynnsharwood